# Generated by Django 4.0.3 on 2023-07-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0007_alter_borrow_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='seminario',
            field=models.CharField(choices=[('1', 'Seminário Teologia'), ('2', 'Seminário Filosofia'), ('3', 'Menor/Propedêutico')], default=1, max_length=3),
        ),
    ]
